servers:
  hosts:
    cluster-server1:
      ansible_host: 10.69.1.80
    cluster-server2:
      ansible_host: 10.69.1.81
    cluster-server3:
      ansible_host: 10.69.1.82
workers:
  host:
    cluster-worker1:
      ansible_host: 10.69.1.83
    cluster-worker2:
      ansible_host: 10.69.1.84
    cluster-worker3:
      ansible_host: 10.69.1.85